### ISSUE TITLE
Replace Google API Source with Local Panos

### ISSUE THREAD

**Issue by pegues** [enricofer/streetmeasure#1]
How could I replace the Google API with my own local panos? I have the exact same format as Google in my demo, using Pano IDs, and the exact same directory and image structure and naming convention, and using a geojson file identical to Google. I just need to change the source to my local. Is this possible?

**Comment by enricofer** [comment]
streetmeasure fetch google streetview panoramas and depth maps using the following external libraries:
PanomNom.js 
GSVPanoDepth.js 
so if you want to point your own panorama repository you have to edit in there.

**Comment by kamillasak** [comment]
@pegues have You replace google api with own panoramas successfull?
