### ISSUE TITLE
own panoramas

### ISSUE THREAD

**Issue by kamillasak** [enricofer/streetmeasure#2]
hello, anyone achived using that on own panoramas?

**Comment by enricofer** [comment]
Some needed libraries are no longer working: https://github.com/proog128/GSVPanoDepth.js

**Comment by kamillasak** [comment]
i was able to repair that and working on streetview. but i wonder if it possible to achive that on own panoramas set

**Comment by enricofer** [comment]
If you have have fixes for that libraries, please submit them.
The application works with remote google panoramas and there is no hope to work with a local own image set.

**Comment by enricofer** [comment]
Upstream libraries have been updated and now streetmeasure tool is working again.
